# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://itmasterdigital.github.io
title: IT-Master.digital
email: info@hhz.de
author: Christian Decker
description: Services Computing ist ein IT Masterstudiengang am Herman Hollerith Zentrum Böblingen für eine berufsbegleitende Ausbildung in innovativen Kernthemen der Wirtschaftsinformatik für digitale Unternehmen und das Digital Business.
copyright: 'Copyright &copy; 2018 Christian Decker. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

application:
  - title: Bewerben bis 15.Juli 2018
    icon: calendar
    url: https://hisinone.reutlingen-university.de/

social:
  - title: Mail
    icon: envelope
    url: mailto:info@hhz.de
  - title: twitter
    icon: twitter
    url: https://twitter.com/hhz_bb
  - title: facebook
    icon: facebook
    url: https://www.facebook.com/boeblingen.hhz
  - title: instagram
    icon: instagram
    url: https://www.instagram.com/hhz_bb
  - title: youtube
    icon: youtube
    url: https://www.youtube.com/channel/UCrZIUkPESAzAQKboKxzjIIA
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: linkedin
#    url: 
